# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: https://i.loli.net/2018/09/22/5ba60201360c9.png

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: https://i.loli.net/2018/09/22/5ba60201360c9.png

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  7299: https://www.mmbbao.com
  Love: Love
  Tutorial: archives

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/MMBBao
  weibo: http://weibo.com/ccccchenyu
  twitter: https://twitter.com/ChenYu_cccc
  mail: mailto:chenyu.cccc@live.com
  
  # widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: <ul><li><a href="https://www.mmbbao.com">如何自定义这里的内容(配置教程)?</a></li></ul>

